name: "Stratum"
version: "0.0.1"
slug: "ha-stratum"
description: "A fully customizable Home Assistant dashboard."
url: "https://github.com/user83749/ha-stratum"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "services"
boot: "auto"
ingress: true
ingress_port: 5173
panel_icon: "mdi:view-dashboard"
panel_title: "Stratum"
map:
  - "config:rw"
  - "share:rw"
  - "ssl"
options:
  hass_url: "http://homeassistant.local:8123"
schema:
  hass_url: str?
