name: "Stratum (Fixed)"
version: "1.0.4"
slug: "ha-stratum-fixed"
description: "A fully customizable Home Assistant dashboard."
url: "https://github.com/user83749/ha-stratum"

# GitHub Container Registry image
image: "ghcr.io/user83749/ha-stratum/{arch}-addon-ha-stratum"

arch:
  - aarch64
  - amd64
  - armv7

startup: "services"
boot: "auto"
init: false

ingress: true
ingress_stream: true
ingress_port: 5173
panel_icon: "mdi:view-dashboard"
panel_title: "Stratum"
panel_admin: false

apparmor: true
hassio_api: true

ports:
  5173/tcp: null

map:
  - "config:rw"
  - "share:rw"
  - "ssl"

options: {}
schema: {}
