name: "Stratum"
version: "0.0.15"
slug: "ha-stratum"
description: "A fully customizable Home Assistant dashboard."
url: "https://github.com/user83749/ha-stratum"

# Docker Hub image â€” built by home-assistant/builder, pulled on install
image: "user83749/addon-ha-stratum-{arch}"

arch:
  - aarch64
  - amd64
  - armv7

startup: "services"
boot: "auto"
init: false

ingress: true
ingress_stream: true
ingress_port: 5173
panel_icon: "mdi:view-dashboard"
panel_title: "Stratum"
panel_admin: false

apparmor: true
hassio_api: true

ports:
  5173/tcp: null

map:
  - "config:rw"
  - "share:rw"
  - "ssl"

options: {}
schema: {}
