name: "Stratum"
version: "1.1.3"
slug: "ha-stratum-v5"
description: "A modern Svelte 5 Home Assistant dashboard"
url: "https://github.com/user83749/ha-stratum"
image: "ghcr.io/user83749/ha-stratum/{arch}-addon-ha-stratum"

arch:
  - aarch64
  - amd64

# Application boot configuration
init: false
startup: "services"
boot: "auto"

ingress: true
ingress_stream: true

# Use internal port for ingress automatically
ports:
  8099/tcp: null

apparmor: true
hassio_api: true

panel_icon: "mdi:view-dashboard"
panel_title: "Stratum"
panel_admin: false

options: {}
schema: {}
